version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tosinakinosho"
    assignees:
      - "tosinakinosho"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"

  # Enable security updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "security"
      - "dependencies"
    reviewers:
      - "tosinakinosho"

  # Documentation site dependencies (Docusaurus in /docs)
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tosinakinosho"
    assignees:
      - "tosinakinosho"
    commit-message:
      prefix: "deps(docs)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "documentation"

  # Documentation site security updates
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "security"
      - "dependencies"
      - "documentation"
    reviewers:
      - "tosinakinosho"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "tosinakinosho"
    labels:
      - "github-actions"
      - "dependencies"
